import 'package:get/get.dart';

class Language extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    //ENGLISH LANGUAGE
    'en_US': {
      'absence': 'Absence',
      'academicYear': 'Academic Year',
      'account': 'Account',
      'activities': 'Activities',
      'allowNotification': 'Allow Notification',
      'announcements': 'Announcements',
      'arabic': 'Arabic',
      'ask': 'Ask',
      'attachments': 'Attachments',
      'attendance': 'Attendance',
      'attendanceDay': 'Attendance by Day',
      'attendancePeriod': 'Attendance by Period',
      'badResponseMsg': "Bad response format 👎",
      'body': 'Body',
      'bodyEmpty': 'Message body cannot be empty',
      'certificate': 'Certificate',
      'chat': 'Chat',
      'compose': 'Compose',
      'couldFind': "Couldn't find the post 😱",
      'createdDate': 'Created Date : ',
      'date': 'Date :',
      'doubleTapExit': 'Double tap the back button to exit',
      'download': 'Download',
      'english': 'English',
      'eventCalender': 'Event Calender',
      'examinations': 'Examinations',
      'examTable': 'Exam Time Table',
      'feeReport': 'Fee Report',
      'filter': 'Filter',
      'forgotPass': 'Forgot Password?',
      'going': 'Going',
      'home': 'Home',
      'homeWork': 'Homework',
      'inbox': 'Mail',
      'language': 'Language',
      'languageChoose': 'Choose Language',
      'lastUpdatedOn': 'Last updated on',
      'library': 'Library',
      'login': 'Login',
      'loginEasily': 'Want to login easily?',
      'loginQR': 'Login with QR CODE',
      'logOut': 'Logout',
      'mayBe': 'May Be',
      'mail': 'Mail',
      'mailTo': 'to',
      'more': 'More',
      'noDataText': 'No data available !',
      'noInternetConnection': 'No Internet connection 😑',
      'noInternetDescription': 'Please connect to internet and try again',
      'noInternetText': 'No Internet',
      'notGoing': 'Not Going',
      'notification': 'Notification',
      'notifyPermissionText':
      'For easy working of downloads, please allow notifications and enable Notification centre and Banner',
      'ok': 'OK',
      'password': 'Password',
      'photoGallery': 'Photo Gallery',
      'postedOn': 'Posted on',
      'premium': 'Premium',
      'profile': 'Profile',
      'reportCard': 'Report Card',
      'requireUserName': 'User Name is required !',
      'requireUserPass': 'Password is required !',
      'scheduledOn': 'Scheduled on',
      'search': 'Search',
      'selectChild': 'Select Your Child',
      'selectTo': 'Please specify recipient',
      'selectRecipient': 'Select Recipient',
      'send': 'Send',
      'sentMail': 'Sent Mail',
      'somethingWrong':
      'Something went wrong. Please try again after some time',
      'subject': 'Subject',
      'subjectEmpty': 'Subject cannot be empty',
      'submissionDate': 'Submission Date : ',
      'timeTable': 'Time Table',
      'tryAgain': 'Try Again',
      'to': ' To ',
      'totalAbsence': 'Total Absence',
      'upcomingEvents': 'Upcoming Events',
      'userName': 'User Name',
      'watchKids': 'Watch Your Kids Live',
      'watchNow': 'Watch Now',
      'weekPlan': 'Weekly Plan',
      'welcomeHome': 'Welcome Home',
      'worksheet': 'Worksheet',
      'yourAnswer': 'Your Answer: ',
      'yourScore': 'Your Score: ',
    },
    //ARABIC LANGUAGE
    'ar_KW': {
      'absence': 'غياب',
      'academicYear': 'السنة الدراسي,',
      'account': 'الحساب',
      'activities': 'أنشطة',
      'allowNotification': 'السماح للتنبيهات',
      'announcements': 'الإعلانات',
      'arabic': 'عربي',
      'ask': 'اسأل',
      'attachments': 'المرفقات',
      'attendance': 'الغياب',
      'attendanceDay': 'الحضور اليومي',
      'attendancePeriod': 'الحضور في الحصص',
      'badResponse': "تنسيق استجابة سيئ 👎",
      'body': 'رسالة',
      'bodyEmpty': 'لا يمكن ترك نص الرسالة فارغًا',
      'certificate': 'شهادة',
      'chat': 'محادثة',
      'compose': 'رسالة جديدة',
      'couldFind': "تعذر العثور على المنشور 😱",
      'createdDate': 'تاريخ الإنشاء : ',
      'date': 'تاريخ :',
      'doubleTapExit': 'انقر نقرًا مزدوجًا فوق زر الرجوع للخروج',
      'download': 'تحميل',
      'english': 'إنجليزي',
      'eventCalender': 'تقويم الأحداث',
      'examinations': 'الامتحانات',
      'examTable': 'جدول الامتحان',
      'feeReport': 'تقرير الرسوم',
      'filter': 'تصفية',
      'forgotPass': 'هل نسيت كلمة السر؟',
      'going': 'مهتم',
      'home': ' الرئيسية',
      'homeWork': 'الواجب المنزلي',
      'inbox': 'صندوق الوارد',
      'language': 'لغة',
      'languageChoose': 'اختر اللغة',
      'lastUpdatedOn': 'آخر تحديث',
      'library': 'مكتبة',
      'login': 'تسجيل الدخول',
      'loginEasily': 'هل تريد تسجيل الدخول بسهولة؟',
      'loginQR': 'تسجيل الدخول باستخدام QR Code',
      'logOut': 'تسجيل خروج',
      'mayBe': 'ربما',
      'mail': 'بريد',
      'mailTo': 'إلى',
      'more': 'المزيد',
      'noDataText': 'لا تتوافر بيانات !',
      'noInternetConnection"': 'لا يوجد اتصال بالإنترنت 😑',
      'noInternetDescription': 'الرجاء الاتصال بالإنترنت وحاول مرة أخرى',
      'noInternetText': 'لا انترنت',
      'notGoing': 'غير مهتم',
      'notification': 'تنبيه',
      'notifyPermissionText':
      'الرجاء تفعيل جميع الصلاحيات و التنبيهات لضمان حصولك على الملفات المحملة بسهولة تامة',
      'ok': 'موافق',
      'password': 'كلمه السر',
      'photoGallery': 'ألبوم الصور',
      'postedOn': 'نشر على',
      'premium': 'غالي',
      'profile': 'الملف الشخصي',
      'reportCard': 'تقرير',
      'requireUserName': 'اسم المستخدم مطلوب !',
      'requireUserPass': 'كلمة المرور مطلوبة !',
      'scheduledOn': 'من المقرر في',
      'search': 'بحث',
      'selectChild': 'اختر طفلك',
      'selectTo': 'يرجى تحديد المستلم',
      'selectRecipient': 'حدد المستلم',
      'send': 'إرسال',
      'sentMail': 'البريد المرسل',
      'somethingWrong':
      'هناك خطأ ما. من فضلك حاول مرة أخرى بعد بعض من الوقت',
      'subject': 'الموضوع',
      'subjectEmpty': 'لا يمكن أن يكون الموضوع فارغًا',
      'submissionDate': 'تاريخ التقديم :',
      'timeTable': 'الجدول',
      'tryAgain': 'حاول ثانية',
      'to': ' إلى ',
      'totalAbsence': 'إجمالي الغياب',
      'upcomingEvents': 'الأحداث القادمة',
      'userName': 'اسم االمستخدم',
      'watchKids': 'شاهد أطفالك مباشرة',
      'watchNow': 'شاهد الآن',
      'weekPlan': 'خطة الأسبوع',
      'welcomeHome': 'مرحبا بك',
      'worksheet': 'ورقة عمل',
      'yourAnswer': 'اجابتك: ',
      'yourScore': 'درجاتك: ',
    },
  };
}
